project_id = "oxkurjhomofoibihhmoq"

[functions.generate-outfits]
verify_jwt = false

[functions.check-incomplete-registrations]
verify_jwt = false

[functions.generate-advanced-report]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.admin-dashboard]
verify_jwt = false
